### ISSUE TITLE
Puedes usar Conekta en Objective-C?

### ISSUE THREAD

**Issue by carlosandresSanchez** [conekta/conekta-ios#2]

**Comment by julianceballos** [comment]
Claro, el unico tema es que debes crear un bridging file, para más info, te dejo el link de documentación de apple:

https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html

**Comment by julianceballos** [comment]
@carlosandresSanchez que paso, pudiste integrar, o necesitas de ayuda?

**Comment by gaf09** [comment]
Hola @julianceballos , estoy intentando integrar la librería de Conekta también en un proyecto creado con objetive-C pero me salen muchos errores del código Swift, los estoy arreglando, pero son varios. Pueden darle soporte a la librería ?

Saludos,

**Comment by julianceballos** [comment]
@gaf09 @carlosandresSanchez ahora el SDK está escrito en objective C, y hemos añadido documentación para integrarlo a proyectos en Swift.
