### ISSUE TITLE
Conekta con archivos Swift

### ISSUE THREAD

**Issue by negry** [conekta/conekta-ios#4]
Quitaron los archivos .swift? estoy usando la libreria con objetive-c en mi proyecto swift pero quiero saber porque quitaron los archivos swift.... el unico inconveniente que tengo con utilizar los archivos de objetive-c es que no me marca ningun tipo de error de sintaxis ni nada por el estilo.

**Comment by julianceballos** [comment]
Hola @negry donde te está dando inconvenientes?

**Comment by negry** [comment]
el inconveniente es que solo al momento de compilar el proyecto me marca cualquier tipo de error en sintaxis o de cualquier otra cosa... con los archivos swift no pasaba eso... es todo por eso quiero saber si eliminaron los archivos swift o que paso? :)

**Comment by julianceballos** [comment]
Hola @negry, te comento que tuvimos que eliminar el código en swift debido a que causaba muchos problemas de integración con los programadores que tienen aplicaciones en objective C. Entonces vamos a ofrecer el código en objective C, para poder dar este soporte más efectivo a los programadores de objective C y de swift.

**Comment by rud0lph09** [comment]
Hola, tengo un problemita. Estoy intentando guardar tarjetas, pero me regresa un mensaje en el método de create para el token en el que dice que no he enviado la tarjeta. Esto es raro, literalmente estoy usando el código del tutorial. No se si sea algo con swift 3 o que onda.
