### ISSUE TITLE
DeviceCollectorSDK

### ISSUE THREAD

**Issue by shadowcarlos** [conekta/conekta-ios#5]
Donde puedo encontrar este archivo? marca error de referencia

**Comment by Janee** [comment]
Hola @shadowcarlos una disculpa, ya no es necesaria dicha librería, ya se corrigió la documentación. Sólo es necesario que añadas Conekta.h

**Comment by shadowcarlos** [comment]
@Janee gracias, una vez que se genero el token de la tarjeta cual es el siguiente paso, mencionan ustedes un servidor , este servidor debería ser implementado por nuestra parte o se pueden genera pagos directamente desde el celular.

**Comment by Janee** [comment]
No es recomendable generar cargos desde la App ya que 3ro podrán acceder a tu key privada y hacer mal uso de la misma. Lo ideal es generar un webservice o similar con el lenguaje de tu agrado para las peticiones.  @shadowcarlos

**Comment by shadowcarlos** [comment]
correcto @Janee , gracias por tu tiempo, saludos.

**Comment by Janee** [comment]
Bonito día :)
