### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by rud0lph09** [conekta/conekta-ios#7]
Hola chicos. Todo funcionaba bien hasta que intente actualizar mi app a iOS 10, con Xcode 8. Y ahora es como si jamas usara el método setNumber: cuando uso create: para el token me regresa un mensaje en el que dice que no envié ninguna tarjeta pero si lo hago :(

**Comment by rud0lph09** [comment]
Por alguna razón se soluciona haciendo un unwrapping extraño. No se si sea correcto pero funciona 


`let conekta = Conekta()
        
        conekta.delegate = self
        
        conekta.publicKey = "key_Dffvvfy47F1oLLmYCrrDz7A"
        
        conekta.collectDevice()
        
        let card = conekta.card()!
        
        card.setNumber("4242424242424242", name: "Julian Ceballos", cvc: "123", expMonth: "10", expYear: "2018")
        
        let token = conekta.token()!
        
        token.card = card
        
        token.create(success: { (data) -> Void in
            print(data)
            }, andError: { (error) -> Void in
                print(error)
        })`

**Comment by Janee** [comment]
Hola @rud0lph09, revisaremos el caso y te contactamos en unos momentos. 
Gracias por tu aportación 👍

**Comment by Janee** [comment]
Hola @rud0lph09 , comenzaremos a trabajar en el testing para que no haya problemas con Xcode 8, pero el detalle que tienes no es un problema, en nuestro README puedes ver un ejemplo que similar a tu código: https://github.com/conekta/conekta-ios#swift
